# Generated by Django 2.2 on 2020-11-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarqueportrecho',
            name='ordem_trecho',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='core.Trecho'),
        ),
        migrations.AlterField(
            model_name='pontoporempresa',
            name='ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_por_empresa', to='core.Ponto'),
        ),
    ]
