# Generated by Django 2.2 on 2020-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201125_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagemdepassageiro',
            name='calculou_ponto_desembarque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='bairro',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='endereco',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='endereco_cittamobi',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
