# Generated by Django 2.2 on 2020-12-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201219_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemPontosLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('atendimento', models.CharField(blank=True, max_length=500, null=True)),
                ('sentido', models.CharField(blank=True, max_length=500, null=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_trechos', to='core.Linha')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_linhas', to='core.Ponto')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdemTrechosLinha',
        ),
    ]
