# Generated by Django 2.2 on 2020-12-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201222_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagemdepassageiro',
            name='partida',
        ),
        migrations.AddField(
            model_name='viagemdepassageiro',
            name='partida_desembarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desembarque_de_passageiros', to='core.Partida'),
        ),
        migrations.AddField(
            model_name='viagemdepassageiro',
            name='partida_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embarque_de_passageiros', to='core.Partida'),
        ),
    ]
