# Generated by Django 2.2 on 2021-01-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201223_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagemdepassageiro',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
