# Generated by Django 2.2 on 2021-01-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_viagemdepassageiro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagemdepassageiro',
            name='linha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagens_de_passageiros', to='core.Linha'),
        ),
    ]
