# Generated by Django 2.2 on 2021-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_linha_eixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='valor_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='linha',
            name='km_ida',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='linha',
            name='km_volta',
            field=models.FloatField(default=0),
        ),
    ]
